package evidence

import (
	"context"
	"fmt"
	"strings"

	"github.com/AnouarMohamed/StateSight/internal/incidents"
	"github.com/AnouarMohamed/StateSight/internal/normalize"
	"github.com/AnouarMohamed/StateSight/pkg/model"
)

const unattributedActor = "not-attributed"

// Attribution links an incident candidate to observed provenance signals.
type Attribution struct {
	Source     string
	Detail     string
	Actor      string
	Confidence float64
	Metadata   map[string]any
}

// AnalysisContext contains the captured inputs that can support evidence claims.
type AnalysisContext struct {
	Application     model.Application
	Source          model.SourceDefinition
	Cluster         model.Cluster
	DesiredRevision string
	Desired         normalize.Snapshot
	Live            normalize.Snapshot
	LiveSummary     map[string]any
}

// Attributor defines evidence generation boundaries.
type Attributor interface {
	BuildAttributions(ctx context.Context, analysis AnalysisContext, candidate incidents.Candidate) ([]Attribution, error)
}

// ProvenanceAttributor creates evidence only from captured analysis signals.
type ProvenanceAttributor struct{}

func (ProvenanceAttributor) BuildAttributions(_ context.Context, analysis AnalysisContext, candidate incidents.Candidate) ([]Attribution, error) {
	attributions := []Attribution{
		buildGitAttribution(analysis, candidate),
		buildLiveAttribution(analysis, candidate),
	}

	if attribution, ok := buildManagedFieldsAttribution(analysis, candidate); ok {
		attributions = append(attributions, attribution)
	}

	return attributions, nil
}

func buildGitAttribution(analysis AnalysisContext, candidate incidents.Candidate) Attribution {
	_, resourcePresent := findResource(analysis.Desired, candidate)
	revision := shortRevision(analysis.DesiredRevision)
	detail := fmt.Sprintf("Desired value for %s was loaded from Git revision %s", candidate.ResourceRef, revision)
	if !resourcePresent {
		detail = fmt.Sprintf("No desired resource matching %s was found in Git revision %s", candidate.ResourceRef, revision)
	}

	return Attribution{
		Source:     "git",
		Detail:     detail,
		Actor:      unattributedActor,
		Confidence: 1,
		Metadata: map[string]any{
			"repository":        analysis.Source.RepoURL,
			"branch":            analysis.Source.DefaultBranch,
			"path":              analysis.Source.Path,
			"revision":          analysis.DesiredRevision,
			"resource_ref":      candidate.ResourceRef,
			"field_path":        candidate.FieldPath,
			"desired_value":     candidate.DesiredValue,
			"resource_present":  resourcePresent,
			"evidence_category": "desired-state-provenance",
		},
	}
}

func buildLiveAttribution(analysis AnalysisContext, candidate incidents.Candidate) Attribution {
	_, resourcePresent := findResource(analysis.Live, candidate)
	collectionSource := summaryString(analysis.LiveSummary, "source")

	source := collectionSource
	detail := fmt.Sprintf("Live value for %s was supplied by the analysis collector", candidate.ResourceRef)
	confidence := 0.5
	trustedObservation := false

	switch collectionSource {
	case "kubectl":
		detail = fmt.Sprintf("Live value for %s was observed through kubectl", candidate.ResourceRef)
		confidence = 1
		trustedObservation = true
	case "synthetic":
		detail = fmt.Sprintf("Live value for %s was generated by the explicit synthetic demo fallback and is not a cluster observation", candidate.ResourceRef)
		confidence = 0
	default:
		if collectionSource == "" {
			source = "live-state"
		} else {
			detail = fmt.Sprintf("Live value for %s was supplied by %s", candidate.ResourceRef, collectionSource)
			confidence = 0.75
		}
	}

	if !resourcePresent {
		if collectionSource == "kubectl" {
			detail = fmt.Sprintf("No live resource matching %s was returned by kubectl", candidate.ResourceRef)
		} else if collectionSource == "synthetic" {
			detail = fmt.Sprintf("Synthetic demo state did not contain a live resource matching %s", candidate.ResourceRef)
		} else {
			detail = fmt.Sprintf("No live resource matching %s was supplied by the analysis collector", candidate.ResourceRef)
		}
	}

	return Attribution{
		Source:     source,
		Detail:     detail,
		Actor:      unattributedActor,
		Confidence: confidence,
		Metadata: map[string]any{
			"collection_source":   collectionSource,
			"cluster_id":          analysis.Cluster.ID,
			"cluster_name":        analysis.Cluster.Name,
			"namespace":           analysis.Application.Namespace,
			"resource_ref":        candidate.ResourceRef,
			"field_path":          candidate.FieldPath,
			"live_value":          candidate.LiveValue,
			"resource_present":    resourcePresent,
			"trusted_observation": trustedObservation,
			"evidence_category":   "live-state-provenance",
		},
	}
}

func buildManagedFieldsAttribution(analysis AnalysisContext, candidate incidents.Candidate) (Attribution, bool) {
	if summaryString(analysis.LiveSummary, "source") == "synthetic" {
		return Attribution{}, false
	}

	resource, ok := findResource(analysis.Live, candidate)
	if !ok {
		return Attribution{}, false
	}

	path, ok := managedFieldsPath(resource, candidate.FieldPath)
	if !ok {
		return Attribution{}, false
	}

	var selected managedFieldsEntry
	matchCount := 0
	for index, entry := range readManagedFields(resource.Raw) {
		if entry.Manager == "" || !ownsManagedPath(entry.Fields, path) {
			continue
		}
		entry.Index = index
		matchCount++
		if matchCount == 1 || entry.newerThan(selected) {
			selected = entry
		}
	}
	if matchCount == 0 {
		return Attribution{}, false
	}

	metadata := map[string]any{
		"manager":             selected.Manager,
		"operation":           selected.Operation,
		"api_version":         selected.APIVersion,
		"observed_at":         selected.Timestamp,
		"resource_ref":        candidate.ResourceRef,
		"field_path":          candidate.FieldPath,
		"matching_entries":    matchCount,
		"evidence_category":   "field-ownership",
		"interpretation_note": "managed field ownership does not prove who introduced the drift",
	}
	return Attribution{
		Source:     "managedFields",
		Detail:     fmt.Sprintf("Kubernetes managedFields reports %s as an owner of %s on the live resource", selected.Manager, candidate.FieldPath),
		Actor:      selected.Manager,
		Confidence: 0.85,
		Metadata:   metadata,
	}, true
}

func findResource(snapshot normalize.Snapshot, candidate incidents.Candidate) (normalize.Resource, bool) {
	if candidate.ResourceKey != "" {
		resource, ok := snapshot.Resources[candidate.ResourceKey]
		return resource, ok
	}
	for _, resource := range snapshot.Resources {
		if resourceRef(resource) == candidate.ResourceRef {
			return resource, true
		}
	}
	return normalize.Resource{}, false
}

func resourceRef(resource normalize.Resource) string {
	apiVersion := strings.TrimSpace(resource.APIVersion)
	if apiVersion == "" {
		apiVersion = "v1"
	}
	return fmt.Sprintf("%s/%s:%s/%s", apiVersion, strings.TrimSpace(resource.Kind), strings.TrimSpace(resource.Namespace), strings.TrimSpace(resource.Name))
}

func shortRevision(revision string) string {
	revision = strings.TrimSpace(revision)
	if revision == "" {
		return "unknown"
	}
	if len(revision) > 12 {
		return revision[:12]
	}
	return revision
}

func summaryString(summary map[string]any, key string) string {
	value, ok := summary[key].(string)
	if !ok {
		return ""
	}
	return strings.TrimSpace(value)
}
