FROM node:26-alpine@sha256:144769ec3f32e8ee36b3cfde91e82bee25d9367b20f31a151f3f7eea3a2a8541 AS build
WORKDIR /src

COPY apps/web/package*.json ./
RUN npm ci --ignore-scripts

COPY apps/web ./
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.31.1-alpine3.23@sha256:85bcbc6b2edd325462560c597d784ecee415024f1c6a004e53ac5f202b8ca561
COPY deployments/docker/nginx.web.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/dist /usr/share/nginx/html

EXPOSE 8080
